### ISSUE TITLE
oss-fuzz reports that libheif is taking too long

### ISSUE THREAD

**Issue by bobfriesenhahn** [strukturag/libheif#1335]
Via oss-fuzz testing of GraphicsMagick, oss-fuzz has detected what seems like a regression in libheif.  Using the rather dated libheif provided with Ubuntu 22.04 LTS, libheif immediately reports "Invalid input: No 'meta' box".

The oss-fuzz issue id is 372815422, and will eventually be visible to all at [graphicsmagick:coder_HEIF_fuzzer: Timeout in coder_HEIF_fuzzer](https://issues.oss-fuzz.com/issues/372815422).

This is the input file which provokes the issue (with .jpg added to the file name to allow upload here):

![clusterfuzz-testcase-minimized-coder_HEIF_fuzzer-5102237891756032 avif](https://github.com/user-attachments/assets/b4037294-c2ad-4762-ae3f-01ae94b1535c)

**Comment by farindk** [comment]
This apparently was fixed already with 365c08dff.

**Comment by bobfriesenhahn** [comment]
I can close this when oss-fuzz reports that the issue is gone in a few days.

**Comment by bobfriesenhahn** [comment]
oss-fuzz issue id 372815422 is now marked as fixed.

**Comment by bobfriesenhahn** [comment]
There is another oss-fuzz issue (372763232) which is confusingly similar to this one and is now marked as fixed.  But unfortunately, [372815422](https://issues.oss-fuzz.com/issues/372815422) is not fixed yet.  That issue is now in a "Pending" state.  I assume that the issue will also be marked as fixed, but reopening until that happens.

**Comment by bobfriesenhahn** [comment]
oss-fuzz has now declared that issue 372815422 is fixed.
